config:
  send_anonymous_usage_stats: false
dbt_aretove:
  outputs:
    dev:
      account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'
      database: '{{ env_var("DBT_ENV_ORG") }}_DBT_DEV'
      password: '{{ env_var("DBT_ENV_SECRET_PASS") }}'
      query_tag: dbt_dev
      role: '{{ env_var("DBT_ENV_ROLE") }}'
      schema: '{{ env_var("DBT_ENV_SECRET_USER") }}'
      threads: 8
      type: snowflake
      user: '{{ env_var("DBT_ENV_SECRET_USER") }}'
      warehouse: '{{ env_var("DBT_ENV_WAREHOUSE") }}'
  target: dev
